[shell]
program = "/opt/homebrew/bin/fish"

[font]
# normal = { family = "Terminus" }
normal = { family = "Terminess Nerd Font Mono" }
# normal = { family = "Hack Nerd Font Mono" }
# normal = { family = "Iosevka Nerd Font Mono" }

# LACKLUSTER COLORS
[colors.primary]
background = '#0A0A0A'

[colors.normal]
# black is gray0
black = '#080808'
red = '#D70000'
green = '#789978'
yellow = '#ffAA88'
blue = '#7788AA'
magenta = '#D7007D'
# cyan is set to lack
cyan = '#708090' 
# white is set to luster
white = '#DEEEED'
